### ISSUE TITLE
UsingCustomWindow: Example incomplete and does not work when completed

### ISSUE THREAD

**Issue by zifredder** [PrismLibrary/Prism-Samples-Wpf#103]
Currently, this example implements a [`Window` as `IDialogWindow`](https://github.com/PrismLibrary/Prism-Samples-Wpf/blob/d6ba9d31459cbf35a40009f4c5e492514e43644c/28-UsingCustomWindow/UsingCustomWindow/Views/MyCustomWindow.xaml.cs#L19), but it is not used anywhere.

Adding the call to open it could be inserted in [`MainWindowViewModel.ShowDialog()`](https://github.com/PrismLibrary/Prism-Samples-Wpf/blob/d6ba9d31459cbf35a40009f4c5e492514e43644c/28-UsingCustomWindow/UsingCustomWindow/ViewModels/MainWindowViewModel.cs#L29) by adding `_dialogService.ShowDialog("MyCustomWindow");`

However, this call throws an exception:
```
Prism.Ioc.ContainerResolutionException
  HResult=0x80131500
  Message=An unexpected error occurred while resolving 'System.Object', with the service name 'MyCustomWindow'
  Source=Prism.Container.Unity
  StackTrace:
   at Prism.Container.Unity.UnityContainerExtension.Resolve(Type type, String name, ValueTuple`2[] parameters)
   at Prism.Dialogs.DialogService.ConfigureDialogWindowContent(String dialogName, IDialogWindow window, IDialogParameters parameters)
   at Prism.Dialogs.DialogService.ShowDialog(String name, IDialogParameters parameters, DialogCallback callback)
   at Prism.Dialogs.IDialogServiceExtensions.ShowDialog(IDialogService dialogService, String name)
   at UsingCustomWindow.ViewModels.MainWindowViewModel.ShowDialog() in C:\Users\<...>\Prism-Samples-Wpf\28-UsingCustomWindow\UsingCustomWindow\ViewModels\MainWindowViewModel.cs:line 26
   at Prism.Commands.DelegateCommand.Execute()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
KeyNotFoundException: No registered type Object with the key MyCustomWindow.

```

What is missing for this to work? It follows the [documentation](https://prismlibrary.com/docs/wpf/dialog-service.html), so I am puzzled.

Thanks in advance. 👍

**Comment by brianlagunas** [comment]
I ran the sample and it worked for me:

<img width="552" alt="image" src="https://github.com/PrismLibrary/Prism-Samples-Wpf/assets/835562/84d5e54e-dbc4-4f7d-a132-50275daf0f6e">

**Comment by zifredder** [comment]
OK alright, now I get it ...
I thought that I need one implementation of `IDialogWindow` _per_ dialog. Now I understood that the `IDialogWindow` implementation will host all dialogs.
Thanks!
